Repository joseluisq/rust-linux-darwin-builder, pull requests merged in 2022-10, with the labels that each got.

#13 Make + Docker: Implement arm64 & amd64 native images
  Makefile
  docker/Dockerfile
  docker/cargo-config.toml
Labels: enhancement, arm64

#14 Linux/Darwin `arm64` cross-compiling support for `x86_64` Docker image
  Makefile
  docker/Dockerfile
Labels: enhancement, arm64, x86_64

#15 Project files structure refactoring
  .dockerignore
  .github/workflows/devel.yml
  .github/workflows/release.yml
  Dockerfile
  LICENSE-MIT
  Makefile
  README.md
  cargo/config.toml
  scripts/git-credential-ghtoken
  tests/hello-world/Cargo.toml
Labels: enhancement

#16 Docker multi-arch support
  .github/workflows/devel.yml
  .github/workflows/release.yml
  scripts/get-latest-release
Labels: enhancement, x86_64

#18 Cirrus CI support for `devel` pipelines
  .cirrus.yml
  .github/workflows/devel.yml
Labels: enhancement, arm64, x86_64, ci, linux
